import type { Metadata } from "next";
import "./globals.css";
import { Nunito } from "next/font/google";
import { cn } from "@/lib/utils";
import ClientProviders from "@/providers/providers";

const nunito = Nunito({ subsets: ["latin", "cyrillic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(`antialiased min-w-[320px]`, nunito.className)}>
        {/* <nav className="absolute bottom-0 left-0 w-full h-7 bg-red-400 text-white font-bold text-sm flex items-center justify-center">
          prisma file has unconfirmed database changes, push them with npx
          prisma db push
        </nav> */}
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
