import { Button } from "@/components/ui/button";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex">
      <div className="sidebar border-r border-slate-300 w-[250px] max-sm:hidden flex h-screen px-3 py-2 flex-col">
        <h1 className="text-4xl font-extrabold text-slate-800 select-none mb-3">
          fluenty
        </h1>
        <Button variant="ghost" className="justify-start">
          Learn
        </Button>
      </div>
      {children}
    </main>
  );
}
